server:
   port: 8888
   servlet:
     context-path: /admin

spring:
   application:
      name: raincat-admin
   profiles:
     active: db
   redis:
      password: foobaredbbexONE123
    # host: 192.168.1.91
    # port: 6379
      sentinel:
          master: mymaster
          nodes:
                - 192.168.1.91:26379
                - 192.168.1.92:26379
                - 192.168.1.93:26379
tx:
  admin :
    userName : admin
    password : admin

