server:
  port: 8888
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.68:3306/test_1?useUnicode=true&characterEncoding=utf8
        username: xiaoyu
        password: Wgj@555888
    application:
      name: consume-service

mybatis:
  type-aliases-package: com.raincat.dubbo.sample.consume.entity
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


raincat:
     tx :
       txManagerUrl: http://192.168.1.109:8761
       serializer: kroy
       nettySerializer: kroy
       compensation: true
       compensationCacheType : db
       txDbConfig :
              driverClassName  : com.mysql.jdbc.Driver
              url :  jdbc:mysql://10.4.4.202:3306/tcc?useUnicode=true&amp;characterEncoding=utf8
              username : root
              password : 123123
logging:
    level:
        root: error
        org.springframework.web: info
        org.apache.ibatis: info
        com.raincat.bonuspoint: info
        com.raincat.lottery: debug
        com.raincat: debug
        io.netty: info

    path: "./logs"


