server:
  port: 8881
  address: 0.0.0.0
  servlet:
    context-path: /pay-service


spring:
    main:
        allow-bean-definition-overriding: true
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/pay?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    application:
      name: pay-service

mybatis:
  type-aliases-package: org.dromara.raincat.springcloud.sample.pay.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
     enabled : false

pay-service :
   ribbon :
     NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule
     MaxAutoRetriesNextServer : 0


logging:
            level:
                root: info
                org.dromara.raincat.core : debug
            path: "./logs"