server:
  port: 8883
  address: 0.0.0.0
  servlet:
    context-path: /wechat-service


spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.1.98:3306/wechat?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
    application:
      name: wechat-service

mybatis:
  type-aliases-package: org.dromara.raincat.springcloud.sample.wechat.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka/
wechat-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule


logging:
            level:
                root: info
                org.dromara.raincat.core : debug
            path: "./logs"

