server:
  port: 8883
  contextPath: /wechat-service
  address: 0.0.0.0

spring:
    datasource:
        driver-class-name:  com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.10.203:3306/wechat?useUnicode=true&characterEncoding=utf8
        username: root
        password: xyz11111111
    application:
      name: wechat-service

mybatis:
  type-aliases-package: com.raincat.springcloud.sample.wechat.entiy
#${random.int[9000,9999]}
eureka:
 client:
     serviceUrl:
       defaultZone: http://192.168.10.203:8761/eureka/
wechat-service :
   ribbon.NFLoadBalancerRuleClassName : com.netflix.loadbalancer.RandomRule


logging:
  level:
      root: info
      com.raincat.core : info
  path: "./logs"

